# SonarQube Cloud Project Configuration
sonar.projectKey=himanshuxreal_DevSecOps_CICD
sonar.organization=himanshuxreal

# Source and Test file locations
sonar.sources=src
sonar.tests=test
sonar.exclusions=**/node_modules/**,**/dist/**

# Encoding
sonar.sourceEncoding=UTF-8
